
export const SERVICE_URL_CYCLIC = "https://hungry-cowboy-boots-boa.cyclic.app"
export const BACKEND_SERVICE_URL = "https://myfirstonlineproject.pythonanywhere.com"
export const AUTH_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjg1ODE2OTAxLCJpYXQiOjE2ODMyMjEzMDEsImp0aSI6IjYxYjhiOWI0ZTZiMzRhZmJiMDM5OGM0MmU2ZjlkMmJkIiwidXNlcl9pZCI6MX0.xXLgSO0_hT2ngKoSMjpL-T_UvgmI8JVUv6ro5Zqv_vs"
