
export const SERVICE_URL_CYCLIC = "https://hungry-cowboy-boots-boa.cyclic.app"
export const BACKEND_SERVICE_URL = "https://myfirstonlineproject.pythonanywhere.com"
export const AUTH_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjg1MTc4NjY2LCJpYXQiOjE2ODI1ODMwNjYsImp0aSI6IjA4YWJlMzI3NmM2NjQ5NGQ5Zjc5ZGFjYWFhMDA0ZDgwIiwidXNlcl9pZCI6NH0.DKKLPcausLqNJJHNUViQRKQr5Rlalx_E7avN0IZXDLA"
